branch-defaults:
  default:
    environment: Johnsbadserver-env
environment-defaults:
  Johnsbadserver-env:
    branch: null
    repository: null
global:
  application_name: johns-bad-server
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
